### ISSUE TITLE
Webhook trigger

### ISSUE THREAD

**Issue by jeppevinkel** [BOLL7708/streaming_widget#12]
A trigger that could be activated by calling a custom webhook url.

This could allow easy integration with 3rd party tools like StreamDeck without having to post commands in a Twitch chat.

**Comment by BOLL7708** [comment]
While not exactly webhooks, the [latest release](https://github.com/BOLL7708/streaming_widget/releases/tag/v4.479) added a relay trigger that uses [OpenVR2WS](https://github.com/BOLL7708/OpenVR2WS) as a relay server, so from any Websockets client it is now possible to trigger events in the widget!
