### ISSUE TITLE
Streaming Widget Login Page Error?

### ISSUE THREAD

**Issue by c0ldvengeance** [BOLL7708/streaming_widget#13]
Login Page says this:
![image](https://user-images.githubusercontent.com/12458935/179699729-463b4af9-cbcb-4b3c-98af-80333af9409a.png)

Release notes says this:
![image](https://user-images.githubusercontent.com/12458935/179699786-4bdf8c27-ea59-425c-a0e5-0c7ec93cd446.png)

I would assume that the Login Page is wrong.

**Comment by BOLL7708** [comment]
Yep, I changed it in one place but not the other, I guess unsurprising as it was late at night. If you check the folders you should be able to find one and not the other so obviously wrong, yes.
